apiVersion: v1
kind: Service
metadata:
  name: weatherforecastservice
spec:
    selector:
        app: weatherforecast
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
    type: LoadBalancer