apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: firebrand-api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: webapi
  template:
    metadata:
      labels:
        app: firebrand-api
        service: webapi
    spec:
      containers:
        - name: webapi
          image: uurdemir/firebrandapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: https://+:443
---
apiVersion: v1
kind: Service
metadata:
  name: firebrand-api-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
      app: firebrand-api
  ports:
  - port: 443
    targetPort: 443
    nodePort: 31001
---